src/Entity/BD.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BDRepository")
 * @Vich\Uploadable
 */
class BD
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $serie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="bd_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $edition;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $collection;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $creation_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $owned_bd_date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $value;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ISBN;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $on_loan;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __toString()
    {
        return $this->getAuthor();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getSerie(): ?string
    {
        return $this->serie;
    }

    public function setSerie(?string $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getEdition(): ?string
    {
        return $this->edition;
    }

    public function setEdition(?string $edition): self
    {
        $this->edition = $edition;

        return $this;
    }

    public function getCollection(): ?string
    {
        return $this->collection;
    }

    public function setCollection(?string $collection): self
    {
        $this->collection = $collection;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getOwnedBdDate(): ?\DateTimeInterface
    {
        return $this->owned_bd_date;
    }

    public function setOwnedBdDate(?\DateTimeInterface $owned_bd_date): self
    {
        $this->owned_bd_date = $owned_bd_date;

        return $this;
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(?int $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getISBN(): ?string
    {
        return $this->ISBN;
    }

    public function setISBN(?string $ISBN): self
    {
        $this->ISBN = $ISBN;

        return $this;
    }

    public function getOnLoan(): ?bool
    {
        return $this->on_loan;
    }

    public function setOnLoan(?bool $on_loan): self
    {
        $this->on_loan = $on_loan;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     */
    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     */
    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

}

src/Form/BDType.php
<?php

namespace App\Form;

use App\Entity\BD;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BDType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('genre',TextType::class, [
                'label' => 'Genre :'
            ])
            ->add('serie',TextType::class, [
                'label' => 'Série :',
                'required' => false
            ])
            ->add('title',TextType::class, [
                'label' => 'Titre :'
            ])
            ->add('imageFile',FileType::class, [
                'label' => 'Couverture :',
                'required' => false
            ])
            ->add('author',TextType::class, [
                'label' => 'Auteur :'
            ])
            ->add('edition',TextType::class, [
                'label' => 'Édition :',
                'required' => false
            ])
            ->add('collection',TextType::class, [
                'label' => 'Collection :',
                'required' => false
            ])
            ->add('creation_date',DateType::class, [
                'label' => 'Date de création :',
                'format' => 'dMy',
                'widget' => 'choice',
                'years' => range(date('Y'), date('Y')-99),
                'required' => false,
                'help' => "Seule l'année est prise en compte",
            ])
            ->add('owned_bd_date',DateType::class, [
                'label' => 'Date de mon exemplaire :',
                'format' => 'dMy',
                'widget' => 'choice',
                'years' => range(date('Y'), date('Y')-99),
                'required' => false,
                'help' => "Seule l'année est prise en compte",
            ])
            ->add('value',IntegerType::class, [
                'label' => 'Cote :',
                'required' => false
            ])
            ->add('price',IntegerType::class, [
                'label' => 'Prix :',
                'required' => false,
                'help' => 'Ne pas rentrer la devise',
            ])
            ->add('comment',TextareaType::class, [
                'label' => 'Commentaire :',
                'required' => false,
                'help' => 'Prêtée à Jean, doublons (...)',
            ])
            ->add('ISBN',TextType::class, [
                'label' => 'ISBN :',
                'required' => false
            ])
            ->add('on_loan',CheckboxType::class, [
                'label' => 'En prêt',
                'required' => false
            ])
            ->add('created_at',DateTimeType::class,  array(
                'label' => "Date d'ajout",
                'data' => new \DateTime()
            ));
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => BD::class,
        ]);
    }
}

src/Controller/BDController.php
<?php

namespace App\Controller;

use App\Entity\BD;
use App\Entity\BDSearch;
use App\Form\BDSearchType;
use App\Form\BDType;
use App\Repository\BDRepository;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bd")
 */
class BDController extends AbstractController
{
    /**
     * @var BDRepository
     */
    private $repository;

    public function __construct(BDRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/list", name="bd_list", methods={"GET"})
     */
    public function list(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new BDSearch();
        $form = $this->createForm(BDSearchType::class, $search);
        $form->handleRequest($request);

        $authors = $this->repository->findByAuthor();
        $genres = $this->repository->findByGenre();
        $series = $this->repository->findBySerie();
        $Bds = $paginator->paginate(
            $this->repository->findAllBdQuery(),
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('bd/list.html.twig', [
            'bds' => $Bds,
            'authors' => $authors,
            'genres' => $genres,
            'series' => $series,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/index", name="bd_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     * @param BDRepository $bDRepository
     * @return Response
     */
    public function index(BDRepository $bDRepository): Response
    {
        return $this->render('bd/index.html.twig', [
            'bds' => $bDRepository->findBD(),
        ]);
    }

    /**
     * @Route("/new", name="bd_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $bD = new BD();
        $form = $this->createForm(BDType::class, $bD);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($bD);
            $entityManager->flush();

            return $this->redirectToRoute('bd_index');
        }

        return $this->render('bd/new.html.twig', [
            'bd' => $bD,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bd_show", methods={"GET"})
     */
    public function show(BD $bD): Response
    {
        return $this->render('bd/show.html.twig', [
            'bd' => $bD,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="bd_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, BD $bD): Response
    {
        $form = $this->createForm(BDType::class, $bD);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('bd_index');
        }

        return $this->render('bd/edit.html.twig', [
            'bd' => $bD,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bd_delete", methods={"DELETE"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, BD $bD): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bD->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($bD);
            $entityManager->flush();
        }

        return $this->redirectToRoute('bd_index');
    }
}

templates/bd/_delete_form.html.twig
<form method="post" action="{{ path('bd_delete', {'id': bd.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bd.id) }}">
    <button class="btn btn-outline-danger">Supprimer</button>
</form>

templates/bd/_form.html.twig
{% block navBar %}
    {% include '/navbars/navbarHomeAdmin.html.twig' %}
{% endblock %}
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col">
                {{ form_start(form) }}
                <div class="row mt-5">
                    <div class='col-md-6'>{{ form_row(form.title) }}</div>
                    <div class='col-md-6'>{{ form_row(form.author) }}</div>
                </div>
                <div class="row">
                    <div class='col-md-6'>{{ form_row(form.serie) }}</div>
                    <div class='col-md-6'>{{ form_row(form.collection) }}</div>
                </div>
                <div class="row">
                    <div class='col-md-6'>{{ form_row(form.edition) }}</div>
                    <div class='col-md-6'>{{ form_row(form.genre) }}</div>
                </div>
                <div class="row">
                    <div class='col'>{{ form_row(form.imageFile) }}</div>
                </div>
                <div class="row">
                    <div class='col-md-6'>{{ form_row(form.creation_date) }}</div>
                    <div class='col-md-6'>{{ form_row(form.owned_bd_date) }}</div>
                </div>
                <div class="row">
                    <div class='col-md-4'>{{ form_row(form.ISBN) }}</div>
                    <div class='col-md-4'>{{ form_row(form.price) }}</div>
                    <div class='col-md-4'>{{ form_row(form.value) }}</div>
                </div>
                <div class="row">
                    <div class='col'>{{ form_row(form.on_loan) }}</div>
                </div>
                <div class="row" style="display: none;">
                    <div class='col'>{{ form_row(form.created_at) }}</div>
                </div>
                {{ form_widget(form) }}
                <button class="btn btn-outline-success mt-3">{{ button_label|default('Enregistrer') }}</button>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</div>

templates/bd/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier{% endblock %}

{% block body %}
    {{ include('bd/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    <div class="col-md-4"><a class="btn btn-outline-primary ml-4 mb-4" href="{{ path('bd_index') }}">retour à la liste</a></div>
    <div class="col-md-4">{{ include('bd/_delete_form.html.twig') }}</div>
{% endblock %}

templates/bd/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BD index{% endblock %}

{% block navBar %}
    {% include '/navbars/navbarHomeAdmin.html.twig' %}
{% endblock %}

{% block body %}
    <div class="container-fluid mt-5">
        <div class="jumbotron text-center">
            <h1 class="mb-5 ">Tableau de bord</h1>
            <table class="table bg-white font-weight-lighter">
                <thead class="table bg-secondary text-white">
                <tr>
                    <th>Id</th>
                    <th>Genre</th>
                    <th>Série</th>
                    <th>Titre</th>
                    <th>Auteur</th>
                    <th>Édition</th>
                    <th>Collection</th>
                    <th>Date de création</th>
                    <th>Date de mon édition</th>
                    <th>Cote</th>
                    <th>Prix</th>
                    <th>Commentaire</th>
                    <th>ISBN</th>
                    <th>En prêt</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for bd in bds %}
                    <tr>
                        <td>{{ bd.id }}</td>
                        <td>{{ bd.genre }}</td>
                        <td>{{ bd.serie }}</td>
                        <td>{{ bd.title }}</td>
                        <td>{{ bd.author }}</td>
                        <td>{{ bd.edition }}</td>
                        <td>{{ bd.collection }}</td>
                        <td>{{ bd.creationDate|date('Y') }}</td>
                        <td>{{ bd.ownedBdDate|date('Y') }}</td>
                        <td>{{ bd.value }}</td>
                        <td>{{ bd.price }}</td>
                        <td>{{ bd.comment }}</td>
                        <td>{{ bd.ISBN }}</td>
                        <td>{{ bd.onLoan ? 'Oui' : 'Non' }}</td>
                        <td>
                            <a class="btn btn-danger mb-3" href="{{ path('bd_show', {'id': bd.id}) }}">voir</a>
                            <a class="btn btn-warning" href="{{ path('bd_edit', {'id': bd.id}) }}">modifier</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="16">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <a class="btn btn-success" href="{{ path('bd_new') }}">Ajouter</a>
        </div>
    </div>

{% endblock %}

templates/bd/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une nouvelle BD{% endblock %}

{% block body %}
    <h1>Create new BD</h1>

    {{ include('bd/_form.html.twig') }}

    <a class="btn btn-outline-primary ml-4" href="{{ path('bd_index') }}">retour à la liste</a>
{% endblock %}

templates/bd/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BD{% endblock %}

{% block navBar %}
    {% include '/navbars/navbarHomeAdmin.html.twig' %}
{% endblock %}

{% block body %}
    {% if is_granted('ROLE_ADMIN') %}
<div class="container mt-5">
    <div class="jumbotron">
        <div class="row">
            <div class="col-2">
                <div class="card mb-3" style="max-width: 540px; max-height: 600px">
                    <div class="card-body">
                        <a class="btn btn-outline-primary mb-4" href="{{ path('bd_index') }}">Liste</a>
                        <a class="btn btn-outline-warning mb-4"
                           href="{{ path('bd_edit', {'id': bd.id}) }}">Modifier</a>
                        {{ include('bd/_delete_form.html.twig') }}
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="row">
                    <div class="col">
                        <div class="card mb-3" style="max-width: 540px; max-height: 600px">
                            <div class="row no-gutters">
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ bd.title }}</h5>
                                        <p class="card-text">{{ bd.author }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="card mb-3 mt-4" style="max-height: 30.5em; max-width: 22em;">
                            <div class="row no-gutters">
                                <div class="col-md-8">
                                    <div class="card-body" style="height: 30.5em; width: 22em;">
                                        <img src="/build/covers/{{ bd.filename }}" alt="bd cover"
                                             style="height: 28em; width: 18em">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card mb-3 ml-5" style="max-width: 540px;">
                    <div class="row no-gutters">
                        <div class="col-md-8">
                            <div class="card-body" style="height: 40.6em">
                                <div class="container ml-4 mt-4">
                                    <p class="card-text"><strong>Genre : </strong>{{ bd.genre }}</p>
                                    <p class="card-text"><strong>Série : </strong>{{ bd.serie }}</p>
                                    <p class="card-text"><strong>Édition : </strong>{{ bd.edition }}</p>
                                    <p class="card-text"><strong>Collection : </strong>{{ bd.collection }}</p>
                                    <p class="card-text"><strong>Date de création
                                            : </strong>{{ bd.creationDate|date('Y') }}</p>
                                    <p class="card-text"><strong>Date de mon édition
                                            : </strong>{{ bd.ownedBdDate|date('Y') }}</p>
                                    <p class="card-text"><strong>Cote : </strong>{{ bd.value }}</p>
                                    <p class="card-text"><strong>Prix : </strong>{{ bd.price }} €</p>
                                    <p class="card-text"><strong>ISBN : </strong>{{ bd.ISBN }}</p>
                                    <p class="card-text"><strong>En prêt
                                            : </strong>{{ bd.onLoan ? 'Oui' : 'Non' }}
                                    </p>
                                    {% if bd.comment %}
                                        <p class="card-text"><strong>Commentaire : </strong>{{ bd.comment }}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="card-body">
                <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for bd in bd %}
                            <div class="carousel-item">
                                <img src="{{ bd.image }}" class="d-block w-100" alt="...">
                            </div>
                        {% endfor %}
                        <div class="carousel-item active" data-interval="10000">
                            <img src="..." class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item" data-interval="2000">
                            <img src="..." class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="..." class="d-block w-100" alt="...">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button"
                       data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleInterval" role="button"
                       data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container mt-5">
    <div class="jumbotron">
        <div class="row">
            <div class="col-4 ml-5">
                <div class="row">
                    <div class="col">
                        <div class="card mb-3" style="max-width: 540px; max-height: 600px">
                            <div class="row no-gutters">
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ bd.title }}</h5>
                                        <p class="card-text">{{ bd.author }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="card mb-3 mt-4" style="max-height: 30.5em; max-width: 22em;">
                            <div class="row no-gutters">
                                <div class="col-md-8">
                                    <div class="card-body" style="height: 30.5em; width: 22em;">
                                        <img src="/build/covers/{{ bd.filename }}" alt="bd cover"
                                             style="height: 28em; width: 18em">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-7">
                <div class="card mb-3 ml-5" style="max-width: 540px;">
                    <div class="row no-gutters">
                        <div class="col-md-8">
                            <div class="card-body" style="height: 40.6em">
                                <div class="container ml-4 mt-4">
                                    <p class="card-text"><strong>Genre : </strong>{{ bd.genre }}</p>
                                    <p class="card-text"><strong>Série : </strong>{{ bd.serie }}</p>
                                    <p class="card-text"><strong>Édition : </strong>{{ bd.edition }}</p>
                                    <p class="card-text"><strong>Collection : </strong>{{ bd.collection }}</p>
                                    <p class="card-text"><strong>Date de création
                                            : </strong>{{ bd.creationDate|date('Y') }}</p>
                                    <p class="card-text"><strong>Date de mon édition
                                            : </strong>{{ bd.ownedBdDate|date('Y') }}</p>
                                    <p class="card-text"><strong>Cote : </strong>{{ bd.value }}</p>
                                    <p class="card-text"><strong>Prix : </strong>{{ bd.price }} €</p>
                                    <p class="card-text"><strong>ISBN : </strong>{{ bd.ISBN }}</p>
                                    <p class="card-text"><strong>En prêt
                                            : </strong>{{ bd.onLoan ? 'Oui' : 'Non' }}
                                    </p>
                                    {% if bd.comment %}
                                        <p class="card-text"><strong>Commentaire : </strong>{{ bd.comment }}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="jumbotron">
        <div class="row">
            <div class="card-body">
                <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for bd in bd %}
                            <div class="carousel-item">
                                <img src="{{ bd.image }}" class="d-block w-100" alt="...">
                            </div>
                        {% endfor %}
                        <div class="carousel-item active" data-interval="10000">
                            <img src="..." class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item" data-interval="2000">
                            <img src="..." class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="..." class="d-block w-100" alt="...">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button"
                       data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleInterval" role="button"
                       data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}


    {% endblock %}